// Modified from OpenGL ES2 header file
GFX_PROC_VOID(glActiveTexture, (GLenum texture), (texture))
GFX_PROC_VOID(glAttachShader, (GLuint program, GLuint shader), (program, shader))
GFX_PROC_VOID(glBindAttribLocation, (GLuint program, GLuint index, const GLchar *name), (program, index, name))
GFX_PROC_VOID(glBindBuffer, (GLenum target, GLuint buffer), (target, buffer))
GFX_PROC_VOID(glBindFramebuffer, (GLenum target, GLuint framebuffer), (target, framebuffer))
GFX_PROC_VOID(glBindRenderbuffer, (GLenum target, GLuint renderbuffer), (target, renderbuffer))
GFX_PROC_VOID(glBindTexture, (GLenum target, GLuint texture), (target, texture))
GFX_PROC_VOID(glBlendColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha), (red, green, blue, alpha))
GFX_PROC_VOID(glBlendEquation, (GLenum mode), (mode))
GFX_PROC_VOID(glBlendEquationSeparate, (GLenum modeRGB, GLenum modeAlpha), (modeRGB, modeAlpha))
GFX_PROC_VOID(glBlendFunc, (GLenum sfactor, GLenum dfactor), (sfactor, dfactor))
GFX_PROC_VOID(glBlendFuncSeparate, (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha), (sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha))
GFX_PROC_VOID(glBufferData, (GLenum target, GLsizeiptr size, const void *data, GLenum usage), (target, size, data, usage))
GFX_PROC_VOID(glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const void *data), (target, offset, size, data))
GFX_PROC(GLenum, glCheckFramebufferStatus, (GLenum target), (target))
GFX_PROC_VOID(glClear, (GLbitfield mask), (mask))
GFX_PROC_VOID(glClearColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha), (red, green, blue, alpha))
GFX_PROC_VOID(glClearDepthf, (GLfloat d), (d))
GFX_PROC_VOID(glClearStencil, (GLint s), (s))
GFX_PROC_VOID(glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha), (red, green, blue, alpha))
GFX_PROC_VOID(glCompileShader, (GLuint shader), (shader))
GFX_PROC_VOID(glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data), (target, level, internalformat, width, height, border, imageSize, data))
GFX_PROC_VOID(glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data), (target, level, xoffset, yoffset, width, height, format, imageSize, data))
GFX_PROC_VOID(glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border), (target, level, internalformat, x, y, width, height, border))
GFX_PROC_VOID(glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height), (target, level, xoffset, yoffset, x, y, width, height))
GFX_PROC(GLuint, glCreateProgram, (void), ())
GFX_PROC(GLuint, glCreateShader, (GLenum type), (type))
GFX_PROC_VOID(glCullFace, (GLenum mode), (mode))
GFX_PROC_VOID(glDeleteBuffers, (GLsizei n, const GLuint *buffers), (n, buffers))
GFX_PROC_VOID(glDeleteFramebuffers, (GLsizei n, const GLuint *framebuffers), (n, framebuffers))
GFX_PROC_VOID(glDeleteProgram, (GLuint program), (program))
GFX_PROC_VOID(glDeleteRenderbuffers, (GLsizei n, const GLuint *renderbuffers), (n, renderbuffers))
GFX_PROC_VOID(glDeleteShader, (GLuint shader), (shader))
GFX_PROC_VOID(glDeleteTextures, (GLsizei n, const GLuint *textures), (n, textures))
GFX_PROC_VOID(glDepthFunc, (GLenum func), (func))
GFX_PROC_VOID(glDepthMask, (GLboolean flag), (flag))
GFX_PROC_VOID(glDepthRangef, (GLfloat n, GLfloat f), (n, f))
GFX_PROC_VOID(glDetachShader, (GLuint program, GLuint shader), (program, shader))
GFX_PROC_VOID(glDisable, (GLenum cap), (cap))
GFX_PROC_VOID(glDisableVertexAttribArray, (GLuint index), (index))
GFX_PROC_VOID(glDrawArrays, (GLenum mode, GLint first, GLsizei count), (mode, first, count))
GFX_PROC_VOID(glDrawElements, (GLenum mode, GLsizei count, GLenum type, const void *indices), (mode, count, type, indices))
GFX_PROC_VOID(glEnable, (GLenum cap), (cap))
GFX_PROC_VOID(glEnableVertexAttribArray, (GLuint index), (index))
GFX_PROC_VOID(glFinish, (void), ())
GFX_PROC_VOID(glFlush, (void), ())
GFX_PROC_VOID(glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer), (target, attachment, renderbuffertarget, renderbuffer))
GFX_PROC_VOID(glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level), (target, attachment, textarget, texture, level))
GFX_PROC_VOID(glFrontFace, (GLenum mode), (mode))
GFX_PROC_VOID(glGenBuffers, (GLsizei n, GLuint *buffers), (n, buffers))
GFX_PROC_VOID(glGenerateMipmap, (GLenum target), (target))
GFX_PROC_VOID(glGenFramebuffers, (GLsizei n, GLuint *framebuffers), (n, framebuffers))
GFX_PROC_VOID(glGenRenderbuffers, (GLsizei n, GLuint *renderbuffers), (n, renderbuffers))
GFX_PROC_VOID(glGenTextures, (GLsizei n, GLuint *textures), (n, textures))
GFX_PROC_VOID(glGetActiveAttrib, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name), (program, index, bufSize, length, size, type, name))
GFX_PROC_VOID(glGetActiveUniform, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name), (program, index, bufSize, length, size, type, name))
GFX_PROC_VOID(glGetAttachedShaders, (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders), (program, maxCount, count, shaders))
GFX_PROC(GLint, glGetAttribLocation, (GLuint program, const GLchar *name), (program, name))
GFX_PROC_VOID(glGetBooleanv, (GLenum pname, GLboolean *data), (pname, data))
GFX_PROC_VOID(glGetBufferParameteriv, (GLenum target, GLenum pname, GLint *params), (target, pname, params))
GFX_PROC(GLenum, glGetError, (void), ())
GFX_PROC_VOID(glGetFloatv, (GLenum pname, GLfloat *data), (pname, data))
GFX_PROC_VOID(glGetFramebufferAttachmentParameteriv, (GLenum target, GLenum attachment, GLenum pname, GLint *params), (target, attachment, pname, params))
GFX_PROC_VOID(glGetIntegerv, (GLenum pname, GLint *data), (pname, data))
GFX_PROC_VOID(glGetProgramiv, (GLuint program, GLenum pname, GLint *params), (program, pname, params))
GFX_PROC_VOID(glGetProgramInfoLog, (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog), (program, bufSize, length, infoLog))
GFX_PROC_VOID(glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint *params), (target, pname, params))
GFX_PROC_VOID(glGetShaderiv, (GLuint shader, GLenum pname, GLint *params), (shader, pname, params))
GFX_PROC_VOID(glGetShaderInfoLog, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog), (shader, bufSize, length, infoLog))
GFX_PROC_VOID(glGetShaderPrecisionFormat, (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision), (shadertype, precisiontype, range, precision))
GFX_PROC_VOID(glGetShaderSource, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source), (shader, bufSize, length, source))
GFX_PROC(const GLubyte*, glGetString, (GLenum name), (name));
GFX_PROC_VOID(glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat *params), (target, pname, params))
GFX_PROC_VOID(glGetTexParameteriv, (GLenum target, GLenum pname, GLint *params), (target, pname, params))
GFX_PROC_VOID(glGetUniformfv, (GLuint program, GLint location, GLfloat *params), (program, location, params))
GFX_PROC_VOID(glGetUniformiv, (GLuint program, GLint location, GLint *params), (program, location, params))
GFX_PROC(GLint, glGetUniformLocation, (GLuint program, const GLchar *name), (program, name))
GFX_PROC_VOID(glGetVertexAttribfv, (GLuint index, GLenum pname, GLfloat *params), (index, pname, params))
GFX_PROC_VOID(glGetVertexAttribiv, (GLuint index, GLenum pname, GLint *params), (index, pname, params))
GFX_PROC_VOID(glGetVertexAttribPointerv, (GLuint index, GLenum pname, void **pointer), (index, pname, pointer))
GFX_PROC_VOID(glHint, (GLenum target, GLenum mode), (target, mode))
GFX_PROC(GLboolean, glIsBuffer, (GLuint buffer), (buffer))
GFX_PROC(GLboolean, glIsEnabled, (GLenum cap), (cap))
GFX_PROC(GLboolean, glIsFramebuffer, (GLuint framebuffer), (framebuffer))
GFX_PROC(GLboolean, glIsProgram, (GLuint program), (program))
GFX_PROC(GLboolean, glIsRenderbuffer, (GLuint renderbuffer), (renderbuffer))
GFX_PROC(GLboolean, glIsShader, (GLuint shader), (shader))
GFX_PROC(GLboolean, glIsTexture, (GLuint texture), (texture))
GFX_PROC_VOID(glLineWidth, (GLfloat width), (width))
GFX_PROC_VOID(glLinkProgram, (GLuint program), (program))
GFX_PROC_VOID(glPixelStorei, (GLenum pname, GLint param), (pname, param))
GFX_PROC_VOID(glPolygonOffset, (GLfloat factor, GLfloat units), (factor, units))
GFX_PROC_VOID(glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels), (x, y, width, height, format, type, pixels))
GFX_PROC_VOID(glReleaseShaderCompiler, (void), ())
GFX_PROC_VOID(glRenderbufferStorage, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height), (target, internalformat, width, height))
GFX_PROC_VOID(glSampleCoverage, (GLfloat value, GLboolean invert), (value, invert))
GFX_PROC_VOID(glScissor, (GLint x, GLint y, GLsizei width, GLsizei height), (x, y, width, height))
GFX_PROC_VOID(glShaderBinary, (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length), (count, shaders, binaryformat, binary, length))
GFX_PROC_VOID(glShaderSource, (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length), (shader, count, string, length))
GFX_PROC_VOID(glStencilFunc, (GLenum func, GLint ref, GLuint mask), (func, ref, mask))
GFX_PROC_VOID(glStencilFuncSeparate, (GLenum face, GLenum func, GLint ref, GLuint mask), (face, func, ref, mask))
GFX_PROC_VOID(glStencilMask, (GLuint mask), (mask))
GFX_PROC_VOID(glStencilMaskSeparate, (GLenum face, GLuint mask), (face, mask))
GFX_PROC_VOID(glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass), (fail, zfail, zpass))
GFX_PROC_VOID(glStencilOpSeparate, (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass), (face, sfail, dpfail, dppass))
GFX_PROC_VOID(glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels), (target, level, internalformat, width, height, border, format, type, pixels))
GFX_PROC_VOID(glTexParameterf, (GLenum target, GLenum pname, GLfloat param), (target, pname, param))
GFX_PROC_VOID(glTexParameterfv, (GLenum target, GLenum pname, const GLfloat *params), (target, pname, params))
GFX_PROC_VOID(glTexParameteri, (GLenum target, GLenum pname, GLint param), (target, pname, param))
GFX_PROC_VOID(glTexParameteriv, (GLenum target, GLenum pname, const GLint *params), (target, pname, params))
GFX_PROC_VOID(glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels), (target, level, xoffset, yoffset, width, height, format, type, pixels))
GFX_PROC_VOID(glUniform1f, (GLint location, GLfloat v0), (location, v0))
GFX_PROC_VOID(glUniform1fv, (GLint location, GLsizei count, const GLfloat *value), (location, count, value))
GFX_PROC_VOID(glUniform1i, (GLint location, GLint v0), (location, v0))
GFX_PROC_VOID(glUniform1iv, (GLint location, GLsizei count, const GLint *value), (location, count, value))
GFX_PROC_VOID(glUniform2f, (GLint location, GLfloat v0, GLfloat v1), (location, v0, v1))
GFX_PROC_VOID(glUniform2fv, (GLint location, GLsizei count, const GLfloat *value), (location, count, value))
GFX_PROC_VOID(glUniform2i, (GLint location, GLint v0, GLint v1), (location, v0, v1))
GFX_PROC_VOID(glUniform2iv, (GLint location, GLsizei count, const GLint *value), (location, count, value))
GFX_PROC_VOID(glUniform3f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2), (location, v0, v1, v2))
GFX_PROC_VOID(glUniform3fv, (GLint location, GLsizei count, const GLfloat *value), (location, count, value))
GFX_PROC_VOID(glUniform3i, (GLint location, GLint v0, GLint v1, GLint v2), (location, v0, v1, v2))
GFX_PROC_VOID(glUniform3iv, (GLint location, GLsizei count, const GLint *value), (location, count, value))
GFX_PROC_VOID(glUniform4f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3), (location, v0, v1, v2, v3))
GFX_PROC_VOID(glUniform4fv, (GLint location, GLsizei count, const GLfloat *value), (location, count, value))
GFX_PROC_VOID(glUniform4i, (GLint location, GLint v0, GLint v1, GLint v2, GLint v3), (location, v0, v1, v2, v3))
GFX_PROC_VOID(glUniform4iv, (GLint location, GLsizei count, const GLint *value), (location, count, value))
GFX_PROC_VOID(glUniformMatrix2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value), (location, count, transpose, value))
GFX_PROC_VOID(glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value), (location, count, transpose, value))
GFX_PROC_VOID(glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value), (location, count, transpose, value))
GFX_PROC_VOID(glUseProgram, (GLuint program), (program))
GFX_PROC_VOID(glValidateProgram, (GLuint program), (program))
GFX_PROC_VOID(glVertexAttrib1f, (GLuint index, GLfloat x), (index, x))
GFX_PROC_VOID(glVertexAttrib1fv, (GLuint index, const GLfloat *v), (index, v))
GFX_PROC_VOID(glVertexAttrib2f, (GLuint index, GLfloat x, GLfloat y), (index, x, y))
GFX_PROC_VOID(glVertexAttrib2fv, (GLuint index, const GLfloat *v), (index, v))
GFX_PROC_VOID(glVertexAttrib3f, (GLuint index, GLfloat x, GLfloat y, GLfloat z), (index, x, y, z))
GFX_PROC_VOID(glVertexAttrib3fv, (GLuint index, const GLfloat *v), (index, v))
GFX_PROC_VOID(glVertexAttrib4f, (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w), (index, x, y, z, w))
GFX_PROC_VOID(glVertexAttrib4fv, (GLuint index, const GLfloat *v), (index, v))
GFX_PROC_VOID(glVertexAttribPointer, (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer), (index, size, type, normalized, stride, pointer))
GFX_PROC_VOID(glViewport, (GLint x, GLint y, GLsizei width, GLsizei height), (x, y, width, height))