// Lifted from SDL_gles2funcs.h
/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2014 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/
SDL_PROC(void, glActiveTexture, (GLenum texture))
SDL_PROC(void, glAttachShader, (GLuint program, GLuint shader))
SDL_PROC(void, glBindAttribLocation, (GLuint program, GLuint index, const GLchar *name))
SDL_PROC(void, glBindBuffer, (GLenum target, GLuint buffer))
SDL_PROC(void, glBindFramebuffer, (GLenum target, GLuint framebuffer))
SDL_PROC(void, glBindRenderbuffer, (GLenum target, GLuint renderbuffer))
SDL_PROC(void, glBindTexture, (GLenum target, GLuint texture))
SDL_PROC(void, glBlendColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
SDL_PROC(void, glBlendEquation, (GLenum mode))
SDL_PROC(void, glBlendEquationSeparate, (GLenum modeRGB, GLenum modeAlpha))
SDL_PROC(void, glBlendFunc, (GLenum sfactor, GLenum dfactor))
SDL_PROC(void, glBlendFuncSeparate, (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha))
SDL_PROC(void, glBufferData, (GLenum target, GLsizeiptr size, const void *data, GLenum usage))
SDL_PROC(void, glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const void *data))
SDL_PROC(GLenum, glCheckFramebufferStatus, (GLenum target))
SDL_PROC(void, glClear, (GLbitfield mask))
SDL_PROC(void, glClearColor, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
SDL_PROC(void, glClearDepthf, (GLfloat d))
SDL_PROC(void, glClearStencil, (GLint s))
SDL_PROC(void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
SDL_PROC(void, glCompileShader, (GLuint shader))
SDL_PROC(void, glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data))
SDL_PROC(void, glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data))
SDL_PROC(void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
SDL_PROC(void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
SDL_PROC(GLuint, glCreateProgram, (void))
SDL_PROC(GLuint, glCreateShader, (GLenum type))
SDL_PROC(void, glCullFace, (GLenum mode))
SDL_PROC(void, glDeleteBuffers, (GLsizei n, const GLuint *buffers))
SDL_PROC(void, glDeleteFramebuffers, (GLsizei n, const GLuint *framebuffers))
SDL_PROC(void, glDeleteProgram, (GLuint program))
SDL_PROC(void, glDeleteRenderbuffers, (GLsizei n, const GLuint *renderbuffers))
SDL_PROC(void, glDeleteShader, (GLuint shader))
SDL_PROC(void, glDeleteTextures, (GLsizei n, const GLuint *textures))
SDL_PROC(void, glDepthFunc, (GLenum func))
SDL_PROC(void, glDepthMask, (GLboolean flag))
SDL_PROC(void, glDepthRangef, (GLfloat n, GLfloat f))
SDL_PROC(void, glDetachShader, (GLuint program, GLuint shader))
SDL_PROC(void, glDisable, (GLenum cap))
SDL_PROC(void, glDisableVertexAttribArray, (GLuint index))
SDL_PROC(void, glDrawArrays, (GLenum mode, GLint first, GLsizei count))
SDL_PROC(void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const void *indices))
SDL_PROC(void, glEnable, (GLenum cap))
SDL_PROC(void, glEnableVertexAttribArray, (GLuint index))
SDL_PROC(void, glFinish, (void))
SDL_PROC(void, glFlush, (void))
SDL_PROC(void, glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
SDL_PROC(void, glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
SDL_PROC(void, glFrontFace, (GLenum mode))
SDL_PROC(void, glGenBuffers, (GLsizei n, GLuint *buffers))
SDL_PROC(void, glGenerateMipmap, (GLenum target))
SDL_PROC(void, glGenFramebuffers, (GLsizei n, GLuint *framebuffers))
SDL_PROC(void, glGenRenderbuffers, (GLsizei n, GLuint *renderbuffers))
SDL_PROC(void, glGenTextures, (GLsizei n, GLuint *textures))
SDL_PROC(void, glGetActiveAttrib, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
SDL_PROC(void, glGetActiveUniform, (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
SDL_PROC(void, glGetAttachedShaders, (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders))
SDL_PROC(GLint, glGetAttribLocation, (GLuint program, const GLchar *name))
SDL_PROC(void, glGetBooleanv, (GLenum pname, GLboolean *data))
SDL_PROC(void, glGetBufferParameteriv, (GLenum target, GLenum pname, GLint *params))
SDL_PROC(GLenum, glGetError, (void))
SDL_PROC(void, glGetFloatv, (GLenum pname, GLfloat *data))
SDL_PROC(void, glGetFramebufferAttachmentParameteriv, (GLenum target, GLenum attachment, GLenum pname, GLint *params))
SDL_PROC(void, glGetIntegerv, (GLenum pname, GLint *data))
SDL_PROC(void, glGetProgramiv, (GLuint program, GLenum pname, GLint *params))
SDL_PROC(void, glGetProgramInfoLog, (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
SDL_PROC(void, glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint *params))
SDL_PROC(void, glGetShaderiv, (GLuint shader, GLenum pname, GLint *params))
SDL_PROC(void, glGetShaderInfoLog, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
SDL_PROC(void, glGetShaderPrecisionFormat, (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision))
SDL_PROC(void, glGetShaderSource, (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source))
SDL_PROC(const GLubyte*, glGetString, (GLenum name));
SDL_PROC(void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat *params))
SDL_PROC(void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint *params))
SDL_PROC(void, glGetUniformfv, (GLuint program, GLint location, GLfloat *params))
SDL_PROC(void, glGetUniformiv, (GLuint program, GLint location, GLint *params))
SDL_PROC(GLint, glGetUniformLocation, (GLuint program, const GLchar *name))
SDL_PROC(void, glGetVertexAttribfv, (GLuint index, GLenum pname, GLfloat *params))
SDL_PROC(void, glGetVertexAttribiv, (GLuint index, GLenum pname, GLint *params))
SDL_PROC(void, glGetVertexAttribPointerv, (GLuint index, GLenum pname, void **pointer))
SDL_PROC(void, glHint, (GLenum target, GLenum mode))
SDL_PROC(GLboolean, glIsBuffer, (GLuint buffer))
SDL_PROC(GLboolean, glIsEnabled, (GLenum cap))
SDL_PROC(GLboolean, glIsFramebuffer, (GLuint framebuffer))
SDL_PROC(GLboolean, glIsProgram, (GLuint program))
SDL_PROC(GLboolean, glIsRenderbuffer, (GLuint renderbuffer))
SDL_PROC(GLboolean, glIsShader, (GLuint shader))
SDL_PROC(GLboolean, glIsTexture, (GLuint texture))
SDL_PROC(void, glLineWidth, (GLfloat width))
SDL_PROC(void, glLinkProgram, (GLuint program))
SDL_PROC(void, glPixelStorei, (GLenum pname, GLint param))
SDL_PROC(void, glPolygonOffset, (GLfloat factor, GLfloat units))
SDL_PROC(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels))
SDL_PROC(void, glReleaseShaderCompiler, (void))
SDL_PROC(void, glRenderbufferStorage, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
SDL_PROC(void, glSampleCoverage, (GLfloat value, GLboolean invert))
SDL_PROC(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height))
SDL_PROC(void, glShaderBinary, (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length))
SDL_PROC(void, glShaderSource, (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length))
SDL_PROC(void, glStencilFunc, (GLenum func, GLint ref, GLuint mask))
SDL_PROC(void, glStencilFuncSeparate, (GLenum face, GLenum func, GLint ref, GLuint mask))
SDL_PROC(void, glStencilMask, (GLuint mask))
SDL_PROC(void, glStencilMaskSeparate, (GLenum face, GLuint mask))
SDL_PROC(void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass))
SDL_PROC(void, glStencilOpSeparate, (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass))
SDL_PROC(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels))
SDL_PROC(void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param))
SDL_PROC(void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat *params))
SDL_PROC(void, glTexParameteri, (GLenum target, GLenum pname, GLint param))
SDL_PROC(void, glTexParameteriv, (GLenum target, GLenum pname, const GLint *params))
SDL_PROC(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels))
SDL_PROC(void, glUniform1f, (GLint location, GLfloat v0))
SDL_PROC(void, glUniform1fv, (GLint location, GLsizei count, const GLfloat *value))
SDL_PROC(void, glUniform1i, (GLint location, GLint v0))
SDL_PROC(void, glUniform1iv, (GLint location, GLsizei count, const GLint *value))
SDL_PROC(void, glUniform2f, (GLint location, GLfloat v0, GLfloat v1))
SDL_PROC(void, glUniform2fv, (GLint location, GLsizei count, const GLfloat *value))
SDL_PROC(void, glUniform2i, (GLint location, GLint v0, GLint v1))
SDL_PROC(void, glUniform2iv, (GLint location, GLsizei count, const GLint *value))
SDL_PROC(void, glUniform3f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
SDL_PROC(void, glUniform3fv, (GLint location, GLsizei count, const GLfloat *value))
SDL_PROC(void, glUniform3i, (GLint location, GLint v0, GLint v1, GLint v2))
SDL_PROC(void, glUniform3iv, (GLint location, GLsizei count, const GLint *value))
SDL_PROC(void, glUniform4f, (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
SDL_PROC(void, glUniform4fv, (GLint location, GLsizei count, const GLfloat *value))
SDL_PROC(void, glUniform4i, (GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
SDL_PROC(void, glUniform4iv, (GLint location, GLsizei count, const GLint *value))
SDL_PROC(void, glUniformMatrix2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
SDL_PROC(void, glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
SDL_PROC(void, glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
SDL_PROC(void, glUseProgram, (GLuint program))
SDL_PROC(void, glValidateProgram, (GLuint program))
SDL_PROC(void, glVertexAttrib1f, (GLuint index, GLfloat x))
SDL_PROC(void, glVertexAttrib1fv, (GLuint index, const GLfloat *v))
SDL_PROC(void, glVertexAttrib2f, (GLuint index, GLfloat x, GLfloat y))
SDL_PROC(void, glVertexAttrib2fv, (GLuint index, const GLfloat *v))
SDL_PROC(void, glVertexAttrib3f, (GLuint index, GLfloat x, GLfloat y, GLfloat z))
SDL_PROC(void, glVertexAttrib3fv, (GLuint index, const GLfloat *v))
SDL_PROC(void, glVertexAttrib4f, (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
SDL_PROC(void, glVertexAttrib4fv, (GLuint index, const GLfloat *v))
SDL_PROC(void, glVertexAttribPointer, (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer))
SDL_PROC(void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height))