require 'rubygems'
require 'rbconfig'

###############################
# BUILD CONFIGURATION VARIABLES
###############################

# Specify the build target - Debug, Release, RelMinSize, RelWithDebug
$buildTarget="Release" # "Debug"

# If 1, then we link against LuaJIT. If 0, we use classic Lua VM.
$doBuildJIT=0

# $buildDebugDefine will trigger the LOOM_DEBUG define if this is a Debug build target
if $buildTarget == "Debug"
  $buildDebugDefine="-DLOOM_IS_DEBUG=1"
else
  $buildDebugDefine="-DLOOM_IS_DEBUG=0"
end

namespace :build do

desc "Builds OS X"

  task :osx do

      puts "== Building OS X =="
      FileUtils.mkdir_p("build/cmake_osx")    
      Dir.chdir("build/cmake_osx") do
        sh "cmake ../../ -DLOOM_BUILD_JIT=#{$doBuildJIT} -G Xcode -DCMAKE_BUILD_TYPE=#{$buildTarget} #{$buildDebugDefine}"
        sh "xcodebuild -configuration #{$buildTarget}"
      end
      
      Dir.chdir("sdk") do
         sh "../artifacts/lsc --symbols --verbose Tests.build"
      end

      #copy bin
      FileUtils.cp_r("sdk/bin", "artifacts/")

  end


end